In [8]:
# from sklearn.datasets import load_boston

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [11]:
train = pd.read_csv("train.csv")

In [12]:
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [14]:
train.drop("Id", axis = 1, inplace = True)

In [15]:
train.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [17]:
train["ExterCond"].unique()

array(['TA', 'Gd', 'Fa', 'Po', 'Ex'], dtype=object)

In [18]:
train = train[['LotFrontage',
 'LotArea',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'HouseStyle',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'ScreenPorch',
 'PoolArea',
 'YrSold',
 'SaleType',
 'SaleCondition',
 'SalePrice']]

In [19]:
train

,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,GarageArea,GarageQual,GarageCond,PavedDrive,ScreenPorch,PoolArea,YrSold,SaleType,SaleCondition,SalePrice
0,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,...,548,TA,TA,Y,0,0,2008,WD,Normal,208500
1,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,...,460,TA,TA,Y,0,0,2007,WD,Normal,181500
2,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,...,608,TA,TA,Y,0,0,2008,WD,Normal,223500
3,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,...,642,TA,TA,Y,0,0,2006,WD,Abnorml,140000
4,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,...,836,TA,TA,Y,0,0,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,...,460,TA,TA,Y,0,0,2007,WD,Normal,175000
1456,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,...,500,TA,TA,Y,0,0,2010,WD,Normal,210000
1457,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,...,252,TA,TA,Y,0,0,2010,WD,Normal,266500
1458,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,...,240,TA,TA,Y,0,0,2010,WD,Normal,142125
1459,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,...,276,TA,TA,Y,0,0,2008,WD,Normal,147500

In [27]:
train["LotFrontage"].describe()[0]

1201.0

In [33]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotFrontage    1201 non-null   float64
 1   LotArea        1460 non-null   int64
 2   Street         1460 non-null   object
 3   Alley          91 non-null     object
 4   LotShape       1460 non-null   object
 5   LandContour    1460 non-null   object
 6   Utilities      1460 non-null   object
 7   LotConfig      1460 non-null   object
 8   LandSlope      1460 non-null   object
 9   Neighborhood   1460 non-null   object
 10  HouseStyle     1460 non-null   object
 11  YearBuilt      1460 non-null   int64
 12  YearRemodAdd   1460 non-null   int64
 13  RoofStyle      1460 non-null   object
 14  GarageArea     1460 non-null   int64
 15  GarageQual     1379 non-null   object
 16  GarageCond     1379 non-null   object
 17  PavedDrive     1460 non-null   object
 18  ScreenPorch    1460 non-null   int64
 19  PoolArea       1460 non-null   int64
 20  YrSold         1460 non-null   int64
 21  SaleType       1460 non-null   object
 22  SaleCondition  1460 non-null   object
 23  SalePrice      1460 non-null   int64
dtypes: float64(1), int64(8), object(15)
memory usage: 273.9+ KB

In [43]:
cols = []
for column in train.columns:
    if len(train[train[column].isna() == False]) != 1460:
        cols.append(column)

In [45]:
train.drop(columns=cols, inplace = True, axis = 1)

/var/folders/6j/0k58mfdd4n77p9l0ggh148rw0000gp/T/ipykernel_6926/22225137.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop(columns=cols, inplace = True, axis = 1)

In [46]:
train

,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,HouseStyle,YearBuilt,YearRemodAdd,RoofStyle,GarageArea,PavedDrive,ScreenPorch,PoolArea,YrSold,SaleType,SaleCondition,SalePrice
0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,2Story,2003,2003,Gable,548,Y,0,0,2008,WD,Normal,208500
1,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,1Story,1976,1976,Gable,460,Y,0,0,2007,WD,Normal,181500
2,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,2Story,2001,2002,Gable,608,Y,0,0,2008,WD,Normal,223500
3,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,2Story,1915,1970,Gable,642,Y,0,0,2006,WD,Abnorml,140000
4,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,2Story,2000,2000,Gable,836,Y,0,0,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,2Story,1999,2000,Gable,460,Y,0,0,2007,WD,Normal,175000
1456,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,1Story,1978,1988,Gable,500,Y,0,0,2010,WD,Normal,210000
1457,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,2Story,1941,2006,Gable,252,Y,0,0,2010,WD,Normal,266500
1458,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,1Story,1950,1996,Hip,240,Y,0,0,2010,WD,Normal,142125
1459,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,1Story,1965,1965,Gable,276,Y,0,0,2008,WD,Normal,147500

In [48]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotArea        1460 non-null   int64
 1   Street         1460 non-null   object
 2   LotShape       1460 non-null   object
 3   LandContour    1460 non-null   object
 4   Utilities      1460 non-null   object
 5   LotConfig      1460 non-null   object
 6   LandSlope      1460 non-null   object
 7   Neighborhood   1460 non-null   object
 8   HouseStyle     1460 non-null   object
 9   YearBuilt      1460 non-null   int64
 10  YearRemodAdd   1460 non-null   int64
 11  RoofStyle      1460 non-null   object
 12  GarageArea     1460 non-null   int64
 13  PavedDrive     1460 non-null   object
 14  ScreenPorch    1460 non-null   int64
 15  PoolArea       1460 non-null   int64
 16  YrSold         1460 non-null   int64
 17  SaleType       1460 non-null   object
 18  SaleCondition  1460 non-null   object
 19  SalePrice      1460 non-null   int64
dtypes: int64(8), object(12)
memory usage: 228.2+ KB

In [ ]:
# hw convert above for loop into list comprehension
# find number of NaN values in each column, replace those NaN values with the mean of the column
# try to plot the bar graph of the sales price with respect to years sold (Yrsold)
# histogram of sales price